### ISSUE TITLE
Socket::PF_PACKET and Socket::PF_LINK undefined on Windows

### ISSUE THREAD

**Issue by patakijv** [steakknife/macaddr#2]
I am running a windows 7 virtual machine and both Socket::PF_PACKET and Socket::PF_LINK are undefined. I can confirm this in the constants list for Socket in irb. 

```
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket.const_defined? :PF_LINK
=> false
irb(main):003:0> Socket.const_defined? :PF_PACKET
=> false
```

Is there another constant that will work instead or is there a reason why these constants may not be defined that is explainable that can lead to a solution?

**Comment by patakijv** [comment]
Although I would like to know how to solve this with some other Socket related constant or method, I managed to patch together a solution that works for windows and/or when those two constants are not defined in my fork https://github.com/logicallabs/macaddr

**Comment by steakknife** [comment]
Thanks for the feedback.  I've pushed a forked gem called `macaddr-steakknife`.

`gem install macaddr-steakknife` / `gem 'macaddr-steakknife', '~> 1.8'`
